services:
  langflow:
    image: langflowai/langflow:latest
    user: root
    restart: always
    ports:
      - "7860:7860"
    depends_on:
      - langflow-postgres
    environment:
      LANGFLOW_DATABASE_URL: postgresql://${LANGFLOW_POSTGRES_USER:-postgres}:${LANGFLOW_POSTGRES_PASSWORD}@langflow-postgres:5432/${LANGFLOW_POSTGRES_DB:-langflow}
      LANGFLOW_CONFIG_DIR: /app/langflow 
      LANGFUSE_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      LANGFUSE_HOST: http://langfuse-web:3000
    volumes:
      - langflow-data:/app/langflow

  langflow-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${LANGFLOW_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${LANGFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LANGFLOW_POSTGRES_DB:-langflow}
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data


volumes:
  langflow-postgres:
  langflow-data:
